CC = gcc

# flags:
# -Wall turns on most compiler warnings
# -lm links the math library
CFLAGS = -Wall -lm

all: part_1 part_2

part_1:
	$(CC) $(CFLAGS) part_1.c -o part_1.o

part_2:
	$(CC) $(CFLAGS) part_2.c -o part_2.o

clean:
	rm *.o *.txt
